[package]
name = "biscuit"
version = "0.1.0"
authors = ["Geoffroy Couprie <geoffroy.couprie@clever-cloud.com>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "^1.0.59"
serde_derive = "^1.0.59"
rand = { version = "0.6", features = ["wasm-bindgen"] }
rand_core = "^0.3"
sha2 = "^0.8"
hmac = "^0.7"
curve25519-dalek = "1.0"
prost = "0.5"
bytes = "0.4"
prost-types = "0.5"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

#[build-dependencies]
#prost-build = "0.5"

[dev-dependencies]
hex = "0.3"
